services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - DATABASE_URL=mysql://root:@db:3306/db_project_it
      - WATCHPACK_POLLING=true
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma db push && npm run dev"

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: db_project_it
    ports:
      - "8081:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
