import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import "../globals.css";
import { ThemeProvider } from "@mui/material";
import theme from "../theme";
import AppHeader from "./components/AppHeader";
import AppFooter from "./components/AppFooter";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { CartProvider } from "../context/CartContext";
import { AuthProvider } from "../context/AuthContext";
import { ThemeContextProvider } from "../context/ThemeContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <AuthProvider>
            <CartProvider>
              <ThemeContextProvider>
                <AppHeader />
                <main style={{ minHeight: '80vh' }}>
                  {children}
                </main>
                <AppFooter />
              </ThemeContextProvider>
            </CartProvider>
          </AuthProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
